### PR TITLE
SWP-95814 Create codeship build

### PR DESCRIPTION
**Pull request by omair-inam**
Setting up CI for Splash fork of [token-bucket](https://github.com/bandwidth-throttle/token-bucket) library.  More details[ in the ticket](https://splashthat.atlassian.net/browse/SWP-95814)

### Dev Testing
[CI passes](https://app.codeship.com/projects/9ce04247-bd73-419a-8874-129c472ba004/builds/9be0897e-1697-4d66-9930-914878ca6a96?component=step_parallel_Run_unit_tests_for_PHP_7.4)

### CODE REVIEW

**Comment by chaitany6143** [comment]
Why are we creating a separate repository as opposed to adding the code to toolbox?

**Review by stfurman — COMMENTED** [review]
No configuration for php8?

**Comment by omair-inam** [comment]
> Why are we creating a separate repository as opposed to adding the code to toolbox?

@chaitany6143 as we discussed separately, it's because I need to customize this (no longer supported) library to add support for 10/20 second rate increments (see #2 )

The repo is already being imported by Toolbox

**Comment by omair-inam** [comment]
> No configuration for php8?

I created a PHP8 config, but in my local testing, I was getting failures (when using Jet CLI to run the codeship steps).  I'll create a follow-up branch with PHP 8 build, but I may need some help getting that working.

**Review by stfurman — APPROVED** [review]

**Review by Timothylock — APPROVED** [review]
As long as we still have toolbox clients that import this (as you mentioned) instead of directly importing from cake/api

**Pull request merged**
